JAFleitas/room-rental-app

client/package-lock.json, client/package.json, client/postcss.config.js, client/src/index.css, client/tailwind.config.js
se agregaron algunas librerias en el front
=> agregando styled components

api/src/db/index.js, api/src/db/models/property.js
Propiedad creada y lectura de modelos desde su ruta.
=> Entidad Property creada

api/src/db/models/Type_User.js, api/src/db/models/User.js, api/src/db/models/property.js
=> creando modelo type_user y modificando pk y fk a UUID

api/src/db/models/comment.js
=> Entidad comment creada.

client/jsconfig.json, client/package-lock.json, client/src/main.jsx, client/src/pages/details-property/detailsProperty.jsx, client/src/pages/details-property/styled-components/index.js, client/src/utilities/getPropertyById.js
se maqueto una parte de la pagina de detalles, falta realizar modales,  y crear la funcionalidad para pedir los datos al back
=> creando page detail property

api/src/app.js, api/src/controllers/PropertyController.js, api/src/index.js, api/src/routes/PropertyRoutes.js, api/src/routes/index.js
=> Be crear propiedad

api/src/db/models/property.js
agregado el atributo imagen de la entidad propiedad, arreglado allowNull mal escrito
=> imagen agregada en modelo propiedad

api/.gitignore, api/package.json, api/src/app.js, api/src/controllers/userController.js, api/src/routes/index.js, api/src/routes/userRoutes.js
Adición de una ruta /api/users/register para la creación de usuarios mediante un formulario de registro
También modifiqué el ruteo ya que estaba repetido tanto en app.js como en routes/index.js
=> Añadiendo registro de usuarios

client/src/components/Filters/Filters.jsx, client/src/components/Filters/styled.jsx, client/src/components/Footer/styled.jsx, client/src/components/SearchBar/SearchBar.jsx, client/src/pages/home/Home.jsx, client/src/routes/RouterApp.jsx
Agrega un componente Home. 
Momentaneamente se utiliza para renderizar el searchBar.
Se agrego un Modal con filtros al SearchBar.
=> Agrega Filtros al SearchBar

client/src/components/AllPropertyCard/AllPropertyCard.jsx, client/src/components/AllPropertyCard/styled.jsx, client/src/components/PropertyCard/styled.jsx
para las cards que mapea el estado y renderiza todas las card.
Falta conseguir el estado y guardarlo en una variable para mapearla, y poner un use state para actualizar el renderizado
=> allCardProperties es un contenedor 

api/src/controllers/userController.js, api/src/routes/userRoutes.js
Añadiendo ruta /api/users/login para el logeo de usuarios
Responde con un token que servirá para la autenticación
Body: email, password
Response: token
=> Añadiendo ruta de login

client/src/components/modal/modal.jsx, client/src/components/modal/styles/index.js, client/src/pages/details-property/components/images-detail/imagesDetail.jsx, client/src/pages/details-property/components/images-detail/styles/index.js, client/src/pages/details-property/detailsProperty.jsx, client/src/pages/details-property/styled-components/index.js, client/src/utilities/formatImages.js
Se modifico el modal para darle mas funcionalidad, se creo una galeria responsive para las fotos de la pagina detalles , y se fueron modularizando componentes, tambien se agrego el metodo lazy para optimizar la carga de imagenes
=> Gonzalo changes modal

api/src/controllers/PropertyController.js, api/src/data/users.json, api/src/db/models/User.js, api/src/index.js, api/src/middlewares/getFiltersProperty.js, api/src/routes/PropertyRoutes.js, api/src/utilities/initDB.js
También se modificó la ruta getProperties para que me devuelva los servicios que posee la propiedad (nombre y id)
=> Añadiendo servicios y tipos de propiedad a la DDBB

client/src/components/Button/Button.jsx, client/src/components/DropDown/DropDown.jsx, client/src/components/DropDown/styled.jsx
El Componente DropDown se lo utiliza en el Boton del Nav. 
El DropDown contiene 3 DropItems: LogIn, SignUp, Profile.
=> Se agrega un componente DropDown

client/src/components/Button/Button.jsx, client/src/components/Button/styled.jsx, client/src/components/DropDown/DropDown.jsx, client/src/components/DropDown/styled.jsx, client/src/components/Filters/Filters.jsx
El Modal se muestra cuando se apreta en el DropDownItem "LogIn"
=> Agrega un LogIn ModalComponent

api/src/controllers/PropertyController.js, api/src/data/properties.json, api/src/db/models/property.js, api/src/routes/PropertyRoutes.js, api/src/utilities/initDB.js
Modifiqué el modelo para que acepte coordenadas, los flat. Además añadí coordenadas en el JSON. Modifiqué la ruta POST para que se suban bien las propiedades referente a la modificación d elos modelos.
=> modificando modelos, JSON y post de propiedades

client/src/components/DropDown/DropDown.jsx, client/src/components/DropDown/styled.jsx
Agrega un Componente Modal para registrarse. 
Tiene 3 campos provisionales: Nombre, Email, Password.
El tamaño responde a cambios según la cantidad de campos que tenga.
El modal se encuentra en la sección 2 del DropDown.
=> Adds a SignUp ModalComponent

api/package.json, api/src/app.js, api/src/db/models/User.js, api/src/passport.js, api/src/routes/index.js
Login social con Facebook, se modificó la entidad Usuario para matchear con JSON de facebook, se quitaron atributos no requeridos en el diagrama
=> login social con Facebook

api/src/db/models/User.js, client/src/pages/details-property/components/images-detail/imagesDetail.jsx, client/src/pages/details-property/detailsProperty.jsx, client/src/pages/home/Home.jsx, client/src/redux/actions/index.js, client/src/redux/reducer/index.js
cada comit tiene una tarea realizada distinta, en resumen, aplique redux a Pages/details y modifique el modelo de User para poder cargar los usuarios
=> Gonzalo get property by

api/README.md, api/src/app.js, api/src/db/models/User.js, api/src/middlewares/getFiltersProperty.js, api/src/utilities/initDB.js
Añadiendo readme con el funcionamiento de los filtros en la ruta GET
Arreglando inicializacion de la DDBB
=> Adding readme api

api/src/controllers/PropertyController.js, api/src/db/models/User.js, api/src/routes/PropertyRoutes.js
Agregada paginación del backend. 
Se debe apuntar las cards nuevamente hacia "properties"
=> Pagination backend

client/src/components/Footer/Footer.jsx, client/src/components/Footer/styled.jsx
=> modificando estilos en footer

api/src/controllers/userController.js, api/src/db/models/User.js
Solucionando errores create user, login y getUserDetail
=> Fix login jwt

api/src/app.js, api/src/passport.js, api/src/routes/userRoutes.js
se agrego el login con google, había una autenticación que me daba error y la cambie por otra
=> login con google

api/src/controllers/userController.js, api/src/middlewares/auth.js, api/src/routes/userRoutes.js
=> Actualizando middleware de autorización

api/package.json, api/src/controllers/servicesController.js, api/src/routes/index.js, api/src/routes/servicesRoutes.js
=> Creando rutas Services

api/package.json, api/src/app.js, api/src/controllers/categoriesController.js, api/src/routes/categoriesRoutes.js, api/src/routes/index.js
=> Route categories

client/src/App.jsx, client/src/components/Filters/Filters.jsx, client/src/components/Filters/Sorters.jsx, client/src/components/Nav/Nav.jsx, client/src/components/SearchBar/SearchBar.jsx, client/src/redux/actions/index.js, client/src/redux/reducer/index.js, client/src/redux/store/index.js
Se añadieron los filtrados en el front y ordenamiento, no he colocado estilos :(
=> Añadiendo filtrado y ordenamiento en el front

client/src/components/DropDown/DropDown.jsx, client/src/pages/profile/profile.jsx, client/src/pages/profile/styled.jsx, client/src/routes/RouterApp.jsx
La pagina profile contiene un titulo, un apartado de info con espacio para una imagen, email y locacion del usuario.
Tambien contiene un espacio para exponer un futuro historial de alquileres. Y, ademas contiene un espacio donde podria exponerse las propiedades que el usuario tiene a disposicion para alquilar, si las tuviera.
La pagina es reponsive y obtiene info del state.user.
=> Se agrega una pagina profile

client/src/components/DropDown/DropDown.jsx, client/src/pages/profile/Components/InfoSubMenu.jsx, client/src/pages/profile/Components/styled.jsx, client/src/pages/profile/OptionalMenu/OptionalMenu.jsx, client/src/pages/profile/OptionalMenu/styled.jsx, client/src/pages/profile/profile.jsx, client/src/pages/profile/styled.jsx, client/src/routes/RouterApp.jsx
Se modifica la disposición de la página Profile. 
Se agrega un menú principal y un submenú. 
El contenido del submenú va a variar según que opción se elija en el menú principal.
La página es responsive.
=> Se modifica la pagina profile

api/package.json, api/src/utilities/email.js
se agrega la función de envió de correo por gmail con la librería nodemailer, también se da de alta correo en gmail para la app
=> Funcion para el envio de email

api/src/controllers/contactController.js, api/src/routes/emailRouter.js, api/src/routes/index.js
se agrega ruta y controlador (contacController)  para el envio de correo al admin
=> ruta de envio de correo a admin

api/src/controllers/contactController.js
Arreglando el envio de email de contacto, aun no eliminar rama
=> Fixing contact email route

client/src/pages/profile/Components/Favorites/Favorites.jsx, client/src/pages/profile/Components/Favorites/styled.jsx, client/src/pages/profile/Components/History/History.jsx, client/src/pages/profile/Components/History/styled.jsx, client/src/pages/profile/MenuRoutes/MenuRoutes.jsx, client/src/routes/RouterApp.jsx
Hay que resolver un par de problemas en esta subpagina:
1. Si usar el metodo planteado en la importacion Favorites o el metodo planteado en el mismo componente
2. Despues de esa decision, correjir los estilos de las cards adaptandolos a la subpagina
3. Hacer que se actualice cuando deslikeamos una propiedad dentro de la misma profile pag
=> Se agrega una subPage en la pagina del Perfil

client/src/components/RentForm/Calendar.jsx, client/src/components/RentForm/Calendar.module.css, client/src/components/RentForm/RentForm.jsx, client/src/components/RentForm/styled.jsx, client/src/pages/details-property/styled-components/index.js, client/src/redux/actions/index.js, client/src/redux/reducer/index.js
=> Se agrega calendario funcional al RentForm

client/src/components/RentForm/Calendar.jsx, client/src/components/RentForm/Calendar.module.css, client/src/components/RentForm/RentForm.jsx, client/src/pages/details-property/detailsProperty.jsx
Falta arreglar el endpoint del back y adaptar la action del front al nuevo endpoint.
=> Se agrega directamente el calendario al Form 

client/src/components/DropDown/DropDown.jsx, client/src/components/DropDown/Login.jsx, client/src/components/DropDown/styled.jsx, client/src/components/Filters/Filters.jsx, client/src/components/RentForm/RentForm.jsx, client/src/components/formAddProperty/form.jsx, client/src/components/formAddProperty/mapContainer.jsx, client/src/pages/404/Error404.jsx, client/src/pages/ForgotPassword/ForgotPassword.jsx, client/src/pages/ForgotPassword/styles.module.css, client/src/pages/Help/Help.jsx, client/src/pages/details-property/detailsProperty.jsx, client/src/redux/actions/index.js, client/src/redux/reducer/index.js, client/src/routes/RouterApp.jsx
Formulario para el forgot password conectado al back
Formulario para enviar mensajes a soporte de la app conectado al back
=> Forgot password and Help

api/src/controllers/PropertyController.js, api/src/controllers/commentController.js, api/src/db/models/User.js, api/src/db/models/comment.js, api/src/db/models/property.js, api/src/routes/commentRoutes.js, api/src/routes/index.js, client/src/components/RentForm/Calendar.module.css, client/src/components/RentForm/RentForm.jsx, client/src/components/RentForm/styled.jsx, client/src/pages/details-property/components/images-detail/imagesDetail.jsx, client/src/pages/details-property/components/map/map.jsx, client/src/pages/details-property/components/reviewCard/reviewCard.jsx, client/src/pages/details-property/components/reviewCard/styles/index.js, client/src/pages/details-property/components/reviewsCarousel/reviewContainer.jsx, client/src/pages/details-property/components/reviewsCarousel/styles/index.js, client/src/pages/details-property/detailsProperty.jsx, client/src/pages/details-property/styled-components/index.js
Se añadio en el get property by id las relaciones con los comentarios
=> CRUD COMENTARIOS

.idea/workspace.xml, api/src/data/properties.json, client/src/components/Filters/Filters.jsx, client/src/components/SearchBar/SearchBar.jsx, client/src/redux/reducer/index.js
=> arreglando filtros

api/src/controllers/rentalControllers.js, client/src/redux/actions/index.js
=> metodos fix

client/src/components/Button/styled.jsx, client/src/components/Filters/styles/index.sort.js, client/src/components/Nav/styled.jsx, client/src/components/SearchBar/styled.js, client/src/components/paginated/styles/index.js, client/src/pages/about-us/styled.jsx, client/src/pages/details-property/styled-components/index.js
Se agregan estilos generales a la pagina.
=> Añade estilos generales a la pagina

api/src/app.js, api/src/controllers/userController.js, api/src/db/models/User.js, api/src/middlewares/auth.js, api/src/routes/userRoutes.js
Pdata: no eliminen la ramaaaaaaaaaa
=> Fixing disable account and adding blocked field un User model

api/src/controllers/rentalControllers.js, api/src/routes/rentalRoutes.js
=> Ruta para admin para traerse todas los alquileres y modificacion de una ruta post a get.

api/src/controllers/PropertyController.js, api/src/routes/PropertyRoutes.js, client/src/components/RentForm/RentForm.jsx, client/src/pages/profile/Components/MyProperties/MyProperties.jsx, client/src/redux/actions/index.js
Se arregló la ruta de back para eliminar propiedad y se la conectó con el botón de eliminar en las ección de mis propiedades. No se puede eliminar una propiedad con alquileres
=> se arregló el calendario y se hizo responsivo. ++

api/src/controllers/rentalControllers.js, api/src/db/models/Property_rental.js, api/src/db/models/User.js, api/src/routes/rentalRoutes.js, client/src/components/RentCard/RentCard.jsx, client/src/components/RentCard/styled.jsx, client/src/pages/profile/MenuRoutes/MenuRoutes.jsx, client/src/pages/profile/styled.jsx, client/src/redux/actions/index.js, client/src/redux/reducer/index.js, client/src/routes/RouterApp.jsx
Se agrega un historial de Rentas en uno de los apartados del perfil.
El historial contiene una RentCard por cada renta que el usuario haya hecho.
Se puede copiar lo mismo para el panel del Admin, solo se deberia cambiar la info que trae.
Todavia no tiene Sorters
=> Añade un historial de Rentas

client/src/pages/about-us/AboutUs.jsx, client/src/pages/about-us/styled.jsx
Agrega estilos a la pagina de OurTeam y la hace responsive.
=> Arreglando estilos de la pagina OurTeam

api/src/controllers/userController.js, client/package.json, client/src/components/formAddProperty/form.jsx, client/src/components/formAddProperty/styles/index.js, client/src/pages/profile/Components/ProfileInfo/ProfileInfo.jsx, client/src/pages/profile/profile.jsx, client/src/utilities/validateForm.js
=> Agregando sweet alert y arreglando bugs

client/src/components/DropDown/DropDown.jsx, client/src/components/DropDown/Login.jsx, client/src/components/auth/logout.jsx
Arreglado cuando da enter en el formulario de login lo loguea y no lo redirige a la ruta de forgot password
Arreglado que el evento onclick del dropdown se pueda hacer fuera de la palabra y funcione
=> Fixing dropdown event

api/src/controllers/paymentMethodController.js, api/src/db/models/PaymentMethod.js, client/src/pages/profile/Components/FormPaymentMethod/FormPaymentMethod.jsx, client/src/pages/profile/Components/PaymentMethods/PaymentMethods.jsx
Cambiando modelos y formularios de metodos de pago
=> Changing model payment method

api/src/controllers/rentalControllers.js, api/src/db/models/Property_rental.js, api/src/db/models/User.js
se resolvieron bugs de rentals
=> bugs rental

client/src/components/DropDown/styled.jsx, client/src/components/auth/logout.jsx, client/src/components/auth/styled.jsx
Se hace responsive el DropDown con las opciones basicas de logueo
=> Se hace responsive el DropDown

api/src/routes/servicesRoutes.js, client/src/pages/AdminDashboard/Categories.jsx, client/src/pages/AdminDashboard/FormCategories.jsx, client/src/pages/AdminDashboard/FormServices.jsx, client/src/pages/AdminDashboard/LeftBar/LeftBar.jsx, client/src/pages/AdminDashboard/Services.jsx, client/src/routes/AdminRoutes.jsx
Añadiendo crud de servicios y categorias al usuario
=> Añadiendo CRUD de servicios y categorias

client/src/components/Button/styled.jsx, client/src/components/DropDown/styled.jsx, client/src/components/Filters/Filters.jsx, client/src/components/Filters/styled.jsx, client/src/components/Filters/styles/index.sort.js, client/src/components/Nav/styled.jsx, client/src/components/PropertyCard/PropertyCard.jsx, client/src/components/PropertyCard/styled.jsx, client/src/components/RentForm/RentForm.jsx, client/src/components/RentForm/styled.jsx, client/src/components/SearchBar/styled.js, client/src/components/paginated/styles/index.js, client/src/pages/AdminDashboard/LeftBar/styles.jsx, client/src/pages/ForgotPassword/styles.module.css, client/src/pages/details-property/styled-components/index.js, client/src/pages/profile/Components/Acount/acount.jsx, client/src/pages/profile/Components/Acount/styled.jsx, client/src/pages/profile/Components/Favorites/styled.jsx, client/src/pages/profile/Components/MyProperties/styled.jsx, client/src/pages/profile/Components/PaymentMethods/PaymentMethods.jsx, client/src/pages/profile/Components/PaymentMethods/styles.module.css, client/src/pages/profile/Components/ProfileInfo/styled.jsx, client/src/pages/profile/Components/RentCard/styled.jsx, client/src/pages/profile/Components/Settings/styled.jsx, client/src/pages/profile/profile.jsx, client/src/pages/profile/styled.jsx, client/src/styles/global.css.js
Se corrigieron algunos estilos y se tradujeron algunas cosas al ingles...
=> Se corrigieron estilos y se traducieron cosas al ingles

api/src/middlewares/getFiltersProperty.js
Bug de propiedad deshabilitada para que no aparezca en home
=> bug delete

api/src/controllers/PropertyController.js, api/src/middlewares/getFiltersProperty.js, api/src/utilities/includeServices.js, client/src/components/Filters/Filters.jsx, client/src/redux/actions/index.js
filtros de servicios y numeros negativos en los filtros
=> Gonzalo filter services

api/src/controllers/commentController.js, api/src/controllers/stripeController.js, client/src/pages/details-property/detailsProperty.jsx
Se arreglaron la ruta comentarios con la actualización de la tabla propiedades=>rating general
=> modificando ruta de rating en comentarios

api/src/controllers/PropertyController.js, client/src/components/Filters/styles/index.sort.js, client/src/components/formAddProperty/form.jsx, client/src/components/formAddProperty/styles/index.js, client/src/utilities/validateForm.js
Modificando las cards al agregar múltiples imágenes al agregar o editar propiedad. Haciendo responsive el form de add/edit property. Añadiendo también sweet alert con redireccionamiento en edit property.
=> Fix add img property

client/src/components/Payment_gateway/Stripe/CardStripe.jsx, client/src/components/Payment_gateway/Stripe/Form_Stripe.jsx, client/src/components/Payment_gateway/paypalButton/styles.jsx, client/src/components/formAddProperty/form.jsx
Agregando loading y redireccionamiento al pagar con stripe y redireccionamiento al crear una propiedad
=> Loading payment stripe
